import { neon } from '@neondatabase/serverless'

function getSql() {
    const connectionString = process.env.DATABASE_URL
    if (!connectionString) {
        throw new Error('DATABASE_URL environment variable is not set')
    }
    return neon(connectionString)
}

export type PostStatus = 'published' | 'draft'

export interface PostSummary {
    id: number
    title: string
    slug: string
    status: PostStatus
    publishedAt: string | null
    // Original full-resolution URL
    heroUrl: string | null
    coverUrl: string | null
    // Responsive variants (generated by Payload imageSizes on upload)
    heroThumbnailUrl: string | null
    heroMediumUrl: string | null
    heroLargeUrl: string | null
    coverThumbnailUrl: string | null
    coverMediumUrl: string | null
    coverLargeUrl: string | null
}

/**
 * Fetch all distinct tags from published posts' customMetaData JSON field.
 */
export async function getDistinctTags(): Promise<string[]> {
    const sql = getSql()
    const rows = await sql`
        SELECT DISTINCT jsonb_array_elements_text(custom_meta_data->'tags') AS tag
        FROM posts
        WHERE _status = 'published'
          AND custom_meta_data IS NOT NULL
          AND custom_meta_data ? 'tags'
        ORDER BY tag
    ` as { tag: string }[]
    return rows.map(r => r.tag)
}

/**
 * Fetch all posts directly from the DB, filtered by status.
 * Includes responsive image variant URLs (thumbnail, medium, large) for optimized rendering.
 * This bypasses Payload CMS's draft versioning system.
 */
export async function getPostsByStatus(status: PostStatus = 'published'): Promise<PostSummary[]> {
    const sql = getSql()
    const rows = await sql`
        SELECT
          p.id,
          p.title,
          p.slug,
          p._status                         AS status,
          p.published_at                    AS "publishedAt",
          m.url                             AS "heroUrl",
          m.sizes_thumbnail_url             AS "heroThumbnailUrl",
          m.sizes_medium_url                AS "heroMediumUrl",
          m.sizes_large_url                 AS "heroLargeUrl",
          m2.url                            AS "coverUrl",
          m2.sizes_thumbnail_url            AS "coverThumbnailUrl",
          m2.sizes_medium_url               AS "coverMediumUrl",
          m2.sizes_large_url                AS "coverLargeUrl"
        FROM posts p
        LEFT JOIN media m  ON p.hero_image_id  = m.id
        LEFT JOIN media m2 ON p.cover_image_id = m2.id
        WHERE p._status = ${status}
        ORDER BY p.published_at DESC NULLS LAST
    ` as PostSummary[]
    return rows
}
