import * as vscode from 'vscode';
import * as path from 'path';

/**
 * Simulates calling the Anti-Gravity CLI and returns a streamable mock markdown response.
 * Uses an async generator to stream markdown blocks chunk-by-chunk to simulate real LLM and CLI execution.
 */
async function* executeAntigravityCLI(prompt: string, context: string): AsyncGenerator<string, void, unknown> {
    const lines = [
        `# 🪐 Anti-Gravity CLI - Execution Simulation\n\n`,
        `Hello from the **Anti-Gravity Coding Assistant**! 🛸\n\n`,
        `I have successfully intercepted your prompt and retrieved the active editor context. Here is the mock execution breakdown:\n\n`,
        `### 💬 Your Prompt\n`,
        `> ${prompt || '*No prompt provided*'}\n\n`,
        `### 📂 Code Context Captured\n`,
        `${context}\n\n`,
        `---\n\n`,
        `### 🚀 Suggested Action & Analysis\n`,
        `Based on the context, here are the simulated recommendations from the **Anti-Gravity Engine**:\n\n`,
        `- **Rule Enforcement**: The strict scope rules are checked. Zero collateral changes detected. 💎\n`,
        `- **Optimization**: Consider using native TypeScript features for robust type safety.\n`,
        `- **Refactoring Proposal**:\n`,
        `  \`\`\`typescript\n`,
        `  // Anti-Gravity optimized stub\n`,
        `  async function handleAntigravityRequest(prompt: string): Promise<string> {\n`,
        `      console.log("Processing prompt:", prompt);\n`,
        `      return "Successfully executed!";\n`,
        `  }\n`,
        `  \`\`\`\n\n`,
        `> [!NOTE]\n`,
        `> This response was generated by a mock placeholder of the \`executeAntigravityCLI\` function.\n`,
        `> In the next phase, we will connect this to the real Anti-Gravity CLI tool! 🌟`
    ];

    for (const line of lines) {
        yield line;
        // Small delay to simulate real streaming speed
        await new Promise(resolve => setTimeout(resolve, 80));
    }
}

export function activate(context: vscode.ExtensionContext) {
    console.log('Extension "chat-panel-with-antigravity-cli" is now active!');

    // Register the chat participant '@antigravity'
    const participant = vscode.chat.createChatParticipant(
        'antigravity.chatParticipant',
        async (request: vscode.ChatRequest, context: vscode.ChatContext, response: vscode.ChatResponseStream, token: vscode.CancellationToken) => {
            // 1. Gather active editor context
            const activeEditor = vscode.window.activeTextEditor;
            let fileContext = '*No active editor open*';

            if (activeEditor) {
                const document = activeEditor.document;
                const fileName = path.basename(document.fileName);
                const languageId = document.languageId;
                
                // Get selected text if any, otherwise get the whole file content (up to 500 lines)
                const selection = activeEditor.selection;
                const selectedText = document.getText(selection);
                const fullText = document.getText();
                
                if (selectedText.trim().length > 0) {
                    fileContext = `**File:** \`${fileName}\` (${languageId})\n` +
                                  `**Selection (Lines ${selection.start.line + 1} - ${selection.end.line + 1}):**\n` +
                                  `\`\`\`${languageId}\n${selectedText}\n\`\`\``;
                } else {
                    const lines = fullText.split('\n');
                    const truncatedText = lines.slice(0, 500).join('\n');
                    const isTruncated = lines.length > 500;
                    
                    fileContext = `**File:** \`${fileName}\` (${languageId})\n` +
                                  `**Full Content (showing first 500 lines):**\n` +
                                  `\`\`\`${languageId}\n${truncatedText}${isTruncated ? '\n... (truncated)' : ''}\n\`\`\``;
                }
            }

            // 2. Print initial status line
            response.markdown(new vscode.MarkdownString('🪐 *Analysing context and running Anti-Gravity CLI...*\n\n'));

            try {
                // 3. Call our placeholder function to execute and stream response
                const generator = executeAntigravityCLI(request.prompt, fileContext);
                for await (const chunk of generator) {
                    // Check if user cancelled the request
                    if (token.isCancellationRequested) {
                        break;
                    }
                    response.markdown(new vscode.MarkdownString(chunk));
                }
            } catch (error) {
                response.markdown(new vscode.MarkdownString(`\n\n❌ **Error during execution:** ${error instanceof Error ? error.message : String(error)}`));
            }
        }
    );

    // Set an icon path if available
    participant.iconPath = vscode.Uri.joinPath(context.extensionUri, 'media', 'antigravity-icon.png');

    context.subscriptions.push(participant);
}

export function deactivate() {}
