// Shared ISR cache for Next.js, stored in Google Cloud Storage.
//
// Cloud Run (minInstances: 0) replaces containers after idle periods and can run several
// at once. Next.js' default cache lives on each container's local disk, so a page
// regenerated by revalidatePath() on one container was lost on the next one, which fell
// back to the build-time HTML. Storing entries and tag invalidations in GCS lets every
// container see the same, latest version.
import { Storage } from '@google-cloud/storage'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'

const FileSystemCache = createRequire(import.meta.url)('next/dist/server/lib/incremental-cache/file-system-cache').default

const ROOT_PREFIX = '_next-isr-cache'
const TAGS_HEADER = 'x-next-cache-tags'
const MAX_TAG_WRITE_ATTEMPTS = 5

let bucket
let buildId

function getBucket() {
  if (!bucket) {
    const storage = new Storage({
      projectId: process.env.GCS_PROJECT_ID || 'noe-shiftica',
      ...(process.env.GCS_KEYFILE_PATH ? { keyFilename: process.env.GCS_KEYFILE_PATH } : {}),
    })
    bucket = storage.bucket(process.env.ISR_CACHE_GCS_BUCKET)
    console.log(`[isr-cache] Using gs://${process.env.ISR_CACHE_GCS_BUCKET}/${ROOT_PREFIX}/${buildId}`)
  }
  return bucket
}

function readBuildId(serverDistDir) {
  try {
    return readFileSync(path.join(serverDistDir, '..', 'BUILD_ID'), 'utf8').trim()
  } catch {
    return 'unknown-build'
  }
}

export function serialize(value) {
  return JSON.stringify(value, function (key, current) {
    const raw = this[key]
    if (raw instanceof Uint8Array) {
      return { __isr: 'buffer', data: Buffer.from(raw.buffer, raw.byteOffset, raw.byteLength).toString('base64') }
    }
    if (raw instanceof Map) {
      return { __isr: 'map', entries: [...raw.entries()] }
    }
    return current
  })
}

export function deserialize(text) {
  return JSON.parse(text, (_key, current) => {
    if (current && current.__isr === 'buffer') return Buffer.from(current.data, 'base64')
    if (current && current.__isr === 'map') return new Map(current.entries)
    return current
  })
}

function isNotFound(error) {
  return error?.code === 404
}

function isPreconditionFailed(error) {
  return error?.code === 412
}

// Same rule as Next.js' own tags manifest: an entry is invalid once any of its tags was
// revalidated after the entry was written. Stale-while-revalidate tags are treated as
// expired, which only makes the next request render fresh instead of serving stale.
export function areTagsInvalidated(tags, lastModified, manifest, now = Date.now()) {
  return tags.some((tag) => {
    const state = manifest[tag]
    if (!state) return false
    if (typeof state.expired === 'number' && state.expired <= now && state.expired > lastModified) return true
    return typeof state.stale === 'number' && state.stale > lastModified
  })
}

function entryTags(entry, ctx) {
  const tags = []
  const header = entry.value?.headers?.[TAGS_HEADER]
  if (typeof header === 'string' && header) tags.push(...header.split(','))
  if (entry.tags) tags.push(...entry.tags)
  if (ctx?.tags) tags.push(...ctx.tags)
  if (ctx?.softTags) tags.push(...ctx.softTags)
  return tags
}

export default class GcsCacheHandler {
  constructor(ctx) {
    const enabled =
      Boolean(process.env.ISR_CACHE_GCS_BUCKET) &&
      !ctx.dev &&
      process.env.NEXT_PHASE !== 'phase-production-build'
    // Local runs and `next build` keep Next.js' default behaviour.
    if (!enabled) return new FileSystemCache(ctx)
    buildId ??= readBuildId(ctx.serverDistDir)
    this.prefix = `${ROOT_PREFIX}/${buildId}`
  }

  entryFile(key) {
    const hash = createHash('sha256').update(key).digest('hex')
    return getBucket().file(`${this.prefix}/entries/${hash}.json`)
  }

  tagsFile(options) {
    return getBucket().file(`${this.prefix}/tags.json`, options)
  }

  async readTags() {
    try {
      const [contents] = await this.tagsFile().download()
      return JSON.parse(contents.toString('utf8'))
    } catch (error) {
      if (isNotFound(error)) return {}
      throw error
    }
  }

  // Reads the manifest pinned to one generation so the conditional write below
  // cannot be based on content newer or older than the generation it checks.
  async readTagsForUpdate() {
    try {
      const [metadata] = await this.tagsFile().getMetadata()
      const [contents] = await this.tagsFile({ generation: metadata.generation }).download()
      return { manifest: JSON.parse(contents.toString('utf8')), generation: Number(metadata.generation) }
    } catch (error) {
      if (isNotFound(error)) return { manifest: {}, generation: 0 }
      throw error
    }
  }

  async get(key, ctx) {
    try {
      const [entryResult, manifest] = await Promise.all([
        this.entryFile(key).download().catch((error) => {
          if (isNotFound(error)) return null
          throw error
        }),
        this.readTags(),
      ])
      if (!entryResult) return null
      const entry = deserialize(entryResult[0].toString('utf8'))
      if (areTagsInvalidated(entryTags(entry, ctx), entry.lastModified, manifest)) return null
      return { lastModified: entry.lastModified, value: entry.value }
    } catch (error) {
      console.error(`[isr-cache] get failed for ${key}; rendering fresh:`, error)
      return null
    }
  }

  async set(key, data, ctx) {
    if (!data) return
    const entry = {
      key,
      lastModified: Date.now(),
      value: data,
      ...(data.kind === 'FETCH' ? { tags: ctx?.tags ?? [] } : {}),
    }
    await this.entryFile(key).save(serialize(entry), {
      resumable: false,
      contentType: 'application/json',
      metadata: { cacheControl: 'no-store' },
    })
  }

  async revalidateTag(tags, durations) {
    const tagList = typeof tags === 'string' ? [tags] : tags
    if (tagList.length === 0) return

    for (let attempt = 1; attempt <= MAX_TAG_WRITE_ATTEMPTS; attempt++) {
      try {
        const { manifest, generation } = await this.readTagsForUpdate()
        const now = Date.now()
        for (const tag of tagList) {
          const current = manifest[tag] ?? {}
          manifest[tag] = durations
            ? {
                ...current,
                stale: now,
                ...(durations.expire !== undefined ? { expired: now + durations.expire * 1000 } : {}),
              }
            : { ...current, expired: now }
        }
        await this.tagsFile().save(JSON.stringify(manifest), {
          resumable: false,
          contentType: 'application/json',
          metadata: { cacheControl: 'no-store' },
          preconditionOpts: { ifGenerationMatch: generation },
        })
        return
      } catch (error) {
        // Another container updated the manifest between our read and write; retry.
        if (isPreconditionFailed(error) && attempt < MAX_TAG_WRITE_ATTEMPTS) continue
        // Logged instead of thrown so a cache outage never fails the CMS save itself.
        console.error(`[isr-cache] revalidateTag failed for ${tagList.join(',')}:`, error)
        return
      }
    }
  }

  resetRequestCache() {}
}
